<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class DistritoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call(ProvinciaSeeder::class);

        $this->command->info('Loading state\'s districts');
        
        DB::table('distritos')->insert(array(
            ["id" => 1, "nombre" => "azul", "provincia_id" => 1],
            ["id" => 2, "nombre" => "puan", "provincia_id" => 1],
            ["id" => 3, "nombre" => "la matanza", "provincia_id" => 1],
            ["id" => 4, "nombre" => "tigre", "provincia_id" => 1],
            ["id" => 5, "nombre" => "25 de mayo", "provincia_id" => 1],
            ["id" => 6, "nombre" => "trenque lauquen", "provincia_id" => 1],
            ["id" => 7, "nombre" => "9 de julio", "provincia_id" => 1],
            ["id" => 8, "nombre" => "lanus", "provincia_id" => 1],
            ["id" => 9, "nombre" => "la plata", "provincia_id" => 1],
            ["id" => 10, "nombre" => "monte", "provincia_id" => 1],
            ["id" => 11, "nombre" => "pehuajo", "provincia_id" => 1],
            ["id" => 12, "nombre" => "san isidro", "provincia_id" => 1],
            ["id" => 13, "nombre" => "pergamino", "provincia_id" => 1],
            ["id" => 14, "nombre" => "alberti", "provincia_id" => 1],
            ["id" => 15, "nombre" => "chascomus", "provincia_id" => 1],
            ["id" => 16, "nombre" => "esteban echeverria", "provincia_id" => 1],
            ["id" => 17, "nombre" => "mercedes", "provincia_id" => 1],
            ["id" => 18, "nombre" => "bahia blanca", "provincia_id" => 1],
            ["id" => 19, "nombre" => "merlo", "provincia_id" => 1],
            ["id" => 20, "nombre" => "junin", "provincia_id" => 1],
            ["id" => 21, "nombre" => "guamini", "provincia_id" => 1],
            ["id" => 22, "nombre" => "lujan", "provincia_id" => 1],
            ["id" => 23, "nombre" => "leandro n.alem", "provincia_id" => 1],
            ["id" => 24, "nombre" => "matanza", "provincia_id" => 1],
            ["id" => 25, "nombre" => "general paz", "provincia_id" => 1],
            ["id" => 26, "nombre" => "san vicente", "provincia_id" => 1],
            ["id" => 27, "nombre" => "cañuelas", "provincia_id" => 1],
            ["id" => 28, "nombre" => "almirante brown", "provincia_id" => 1],
            ["id" => 29, "nombre" => "coronel rosales", "provincia_id" => 1],
            ["id" => 30, "nombre" => "baradero", "provincia_id" => 1],
            ["id" => 31, "nombre" => "saavedra", "provincia_id" => 1],
            ["id" => 32, "nombre" => "brandsen", "provincia_id" => 1],
            ["id" => 33, "nombre" => "general sarmiento", "provincia_id" => 1],
            ["id" => 34, "nombre" => "tapalque", "provincia_id" => 1],
            ["id" => 35, "nombre" => "saladillo", "provincia_id" => 1],
            ["id" => 36, "nombre" => "magdalena", "provincia_id" => 1],
            // ["id" => 37, "nombre" => "gonzales chaves", "provincia_id" => 1],
            ["id" => 38, "nombre" => "general pinto", "provincia_id" => 1],
            ["id" => 39, "nombre" => "navarro", "provincia_id" => 1],
            ["id" => 40, "nombre" => "daireaux", "provincia_id" => 1],
            ["id" => 41, "nombre" => "lobos", "provincia_id" => 1],
            ["id" => 42, "nombre" => "coronel dorrego", "provincia_id" => 1],
            ["id" => 43, "nombre" => "adolfo alsina", "provincia_id" => 1],
            ["id" => 44, "nombre" => "colon", "provincia_id" => 1],
            ["id" => 45, "nombre" => "general arenales", "provincia_id" => 1],
            ["id" => 46, "nombre" => "lincoln", "provincia_id" => 1],
            ["id" => 47, "nombre" => "villarino", "provincia_id" => 1],
            ["id" => 48, "nombre" => "vicente lopez", "provincia_id" => 1],
            ["id" => 49, "nombre" => "bartolome mitre", "provincia_id" => 1],
            ["id" => 50, "nombre" => "exaltacion de la cruz", "provincia_id" => 1],
            ["id" => 51, "nombre" => "salto", "provincia_id" => 1],
            ["id" => 52, "nombre" => "bragado", "provincia_id" => 1],
            ["id" => 53, "nombre" => "zarate", "provincia_id" => 1],
            ["id" => 54, "nombre" => "avellaneda", "provincia_id" => 1],
            ["id" => 55, "nombre" => "ayacucho", "provincia_id" => 1],
            ["id" => 56, "nombre" => "san andres de giles", "provincia_id" => 1],
            ["id" => 57, "nombre" => "tandil", "provincia_id" => 1],
            ["id" => 58, "nombre" => "rivadavia", "provincia_id" => 1],
            ["id" => 59, "nombre" => "patagones", "provincia_id" => 1],
            ["id" => 60, "nombre" => "grl.viamonte", "provincia_id" => 1],
            ["id" => 61, "nombre" => "cnl.de marina leonardo rosales", "provincia_id" => 1],
            ["id" => 62, "nombre" => "balcarce", "provincia_id" => 1],
            ["id" => 63, "nombre" => "tres arroyos", "provincia_id" => 1],
            ["id" => 64, "nombre" => "general villegas", "provincia_id" => 1],
            ["id" => 65, "nombre" => "lomas de zamora", "provincia_id" => 1],
            ["id" => 66, "nombre" => "berisso", "provincia_id" => 1],
            ["id" => 67, "nombre" => "juarez", "provincia_id" => 1],
            ["id" => 68, "nombre" => "grl.pueyrredon", "provincia_id" => 1],
            ["id" => 69, "nombre" => "coronel suarez", "provincia_id" => 1],
            ["id" => 70, "nombre" => "escobar", "provincia_id" => 1],
            ["id" => 71, "nombre" => "carlos casares", "provincia_id" => 1],
            ["id" => 72, "nombre" => "chivilcoy", "provincia_id" => 1],
            ["id" => 73, "nombre" => "berazategui", "provincia_id" => 1],
            ["id" => 74, "nombre" => "quilmes", "provincia_id" => 1],
            // MAL :: ["id" => 75, "nombre" => "torquinst", "provincia_id" => 1],
            ["id" => 76, "nombre" => "3 de febrero", "provincia_id" => 1],
            ["id" => 77, "nombre" => "olavarria", "provincia_id" => 1],
            ["id" => 78, "nombre" => "pellegrini", "provincia_id" => 1],
            ["id" => 79, "nombre" => "general belgano", "provincia_id" => 1],
            ["id" => 80, "nombre" => "florencio varela", "provincia_id" => 1],
            ["id" => 81, "nombre" => "salliquelo", "provincia_id" => 1],
            //["id" => 82, "nombre" => "coronel rosales", "provincia_id" => 1],
            ["id" => 83, "nombre" => "mar chiquita", "provincia_id" => 1],
            ["id" => 84, "nombre" => "general pueyrredon", "provincia_id" => 1],
            ["id" => 85, "nombre" => "campana", "provincia_id" => 1],
            ["id" => 86, "nombre" => "grl.sarmiento", "provincia_id" => 1],
            ["id" => 87, "nombre" => "rojas", "provincia_id" => 1],
            ["id" => 88, "nombre" => "sarmiento", "provincia_id" => 1],
            ["id" => 89, "nombre" => "carmen de areco", "provincia_id" => 1],
            ["id" => 90, "nombre" => "pila", "provincia_id" => 1],
            ["id" => 91, "nombre" => "tres de febrero", "provincia_id" => 1],
            ["id" => 92, "nombre" => "moron", "provincia_id" => 1],
            ["id" => 93, "nombre" => "castelli", "provincia_id" => 1],
            ["id" => 94, "nombre" => "chacabuco", "provincia_id" => 1],
            ["id" => 95, "nombre" => "general viamonte", "provincia_id" => 1],
            ["id" => 96, "nombre" => "rauch", "provincia_id" => 1],
            ["id" => 97, "nombre" => "general belgrano", "provincia_id" => 1],
            ["id" => 98, "nombre" => "tornquist", "provincia_id" => 1],
            ["id" => 99, "nombre" => "necochea", "provincia_id" => 1],
            ["id" => 100, "nombre" => "marcos paz", "provincia_id" => 1],
            ["id" => 101, "nombre" => "carlos tejedor", "provincia_id" => 1],
            ["id" => 102, "nombre" => "san pedro", "provincia_id" => 1],
            ["id" => 103, "nombre" => "general alvarado", "provincia_id" => 1],
            ["id" => 104, "nombre" => "san nicolas", "provincia_id" => 1],
            ["id" => 105, "nombre" => "hipolito yrigoyen", "provincia_id" => 1],
            ["id" => 106, "nombre" => "las flores", "provincia_id" => 1],
            ["id" => 107, "nombre" => "coronel pringles", "provincia_id" => 1],
            ["id" => 108, "nombre" => "general san martin", "provincia_id" => 1],
            ["id" => 109, "nombre" => "benito juarez", "provincia_id" => 1],
            ["id" => 110, "nombre" => "san cayetano", "provincia_id" => 1],
            ["id" => 111, "nombre" => "adolfo gonzales chaves", "provincia_id" => 1],
            ["id" => 112, "nombre" => "dolores", "provincia_id" => 1],
            ["id" => 113, "nombre" => "san antonio", "provincia_id" => 1],
            ["id" => 114, "nombre" => "loberia", "provincia_id" => 1],
            ["id" => 115, "nombre" => "ramallo", "provincia_id" => 1],
            ["id" => 116, "nombre" => "general alvear", "provincia_id" => 1],
            ["id" => 117, "nombre" => "ensenada", "provincia_id" => 1],
            ["id" => 118, "nombre" => "tordillo", "provincia_id" => 1],
            ["id" => 119, "nombre" => "general guido", "provincia_id" => 1],
            ["id" => 120, "nombre" => "general las heras", "provincia_id" => 1],
            ["id" => 121, "nombre" => "general juan madariaga", "provincia_id" => 1],
            ["id" => 122, "nombre" => "general la madrid", "provincia_id" => 1],
            ["id" => 123, "nombre" => "general lavalle", "provincia_id" => 1],
            ["id" => 124, "nombre" => "general rodriguez", "provincia_id" => 1],
            ["id" => 125, "nombre" => "general vllegas", "provincia_id" => 1],
            // ["id" => 126, "nombre" => "adolfo gonzalez chaves", "provincia_id" => 1],
            ["id" => 127, "nombre" => "coronel de marina l.rosales", "provincia_id" => 1],
            ["id" => 128, "nombre" => "bolivar", "provincia_id" => 1],
            ["id" => 129, "nombre" => "san fernando", "provincia_id" => 1],
            ["id" => 130, "nombre" => "capitan sarmiento", "provincia_id" => 1],
            ["id" => 131, "nombre" => "roque perez", "provincia_id" => 1],
            ["id" => 132, "nombre" => "moreno", "provincia_id" => 1],
            ["id" => 133, "nombre" => "laprida", "provincia_id" => 1],
            ["id" => 134, "nombre" => "maipu", "provincia_id" => 1],
            ["id" => 135, "nombre" => "echeverria", "provincia_id" => 1],
            ["id" => 136, "nombre" => "pilar", "provincia_id" => 1],
            ["id" => 137, "nombre" => "coronel de marina l. rosales", "provincia_id" => 1],
            ["id" => 138, "nombre" => "suipacha", "provincia_id" => 1],
            ["id" => 139, "nombre" => "san antonio de areco", "provincia_id" => 1],
            ["id" => 140, "nombre" => "barazategui", "provincia_id" => 1],
            ["id" => 141, "nombre" => "alsina", "provincia_id" => 1],
            ["id" => 142, "nombre" => "leandro n. elem", "provincia_id" => 1],
            ["id" => 143, "nombre" => "grl.san martin", "provincia_id" => 1],
            ["id" => 144, "nombre" => "coronel", "provincia_id" => 1],

            ["id" => 145, "nombre" => "capayan", "provincia_id" => 2],
            ["id" => 146, "nombre" => "andalgala", "provincia_id" => 2],
            ["id" => 147, "nombre" => "el alto", "provincia_id" => 2],
            ["id" => 148, "nombre" => "santa rosa", "provincia_id" => 2],
            ["id" => 149, "nombre" => "ancasti", "provincia_id" => 2],
            ["id" => 150, "nombre" => "paclin", "provincia_id" => 2],
            ["id" => 151, "nombre" => "santa maria", "provincia_id" => 2],
            ["id" => 152, "nombre" => "tinogasta", "provincia_id" => 2],
            ["id" => 153, "nombre" => "la paz", "provincia_id" => 2],
            ["id" => 154, "nombre" => "valle viejo", "provincia_id" => 2],
            ["id" => 155, "nombre" => "antofagasta de la sierra", "provincia_id" => 2],
            ["id" => 156, "nombre" => "belen", "provincia_id" => 2],
            ["id" => 157, "nombre" => "capital", "provincia_id" => 2],
            ["id" => 158, "nombre" => "fray mamerto esquiu", "provincia_id" => 2],
            ["id" => 159, "nombre" => "poman", "provincia_id" => 2],
            ["id" => 160, "nombre" => "ambato", "provincia_id" => 2],

            ["id" => 161, "nombre" => "independencia", "provincia_id" => 3],
            ["id" => 162, "nombre" => "san fernando", "provincia_id" => 3],
            ["id" => 163, "nombre" => "primero de mayo", "provincia_id" => 3],
            ["id" => 164, "nombre" => "fray justo santa maria de oro", "provincia_id" => 3],
            ["id" => 165, "nombre" => "sargento cabral", "provincia_id" => 3],
            ["id" => 166, "nombre" => "general guemes", "provincia_id" => 3],
            ["id" => 167, "nombre" => "tapenaga", "provincia_id" => 3],
            ["id" => 168, "nombre" => "chacabuco", "provincia_id" => 3],
            ["id" => 169, "nombre" => "libertador grl.san martin", "provincia_id" => 3],
            ["id" => 170, "nombre" => "25 de mayo", "provincia_id" => 3],
            ["id" => 171, "nombre" => "12 de octubre", "provincia_id" => 3],
            ["id" => 172, "nombre" => "comandante fernandez", "provincia_id" => 3],
            ["id" => 173, "nombre" => "quitilipi", "provincia_id" => 3],
            ["id" => 174, "nombre" => "mayor luis j.fontana", "provincia_id" => 3],
            ["id" => 175, "nombre" => "libertad", "provincia_id" => 3],
            ["id" => 176, "nombre" => "bermejo", "provincia_id" => 3],
            ["id" => 177, "nombre" => "almirante brown", "provincia_id" => 3],
            ["id" => 178, "nombre" => "meyor luis j.fontana", "provincia_id" => 3],
            ["id" => 179, "nombre" => "general belgrano", "provincia_id" => 3],
            ["id" => 180, "nombre" => "libertador grl. san martin", "provincia_id" => 3],
            ["id" => 181, "nombre" => "general donovan", "provincia_id" => 3],
            ["id" => 182, "nombre" => "san lorenzo", "provincia_id" => 3],
            ["id" => 183, "nombre" => "lebertador grl.san martin", "provincia_id" => 3],
            ["id" => 184, "nombre" => "maipu", "provincia_id" => 3],
            ["id" => 185, "nombre" => "o'higgins", "provincia_id" => 3],
            ["id" => 186, "nombre" => "9 de julio", "provincia_id" => 3],
            ["id" => 187, "nombre" => "libertador san martin", "provincia_id" => 3],

            ["id" => 188, "nombre" => "rio senguerr", "provincia_id" => 4],
            ["id" => 189, "nombre" => "martires", "provincia_id" => 4],
            ["id" => 190, "nombre" => "escalante", "provincia_id" => 4],
            ["id" => 191, "nombre" => "gaiman", "provincia_id" => 4],
            ["id" => 192, "nombre" => "sarmiento", "provincia_id" => 4],
            ["id" => 193, "nombre" => "cushamen", "provincia_id" => 4],
            ["id" => 194, "nombre" => "florentino ameghino", "provincia_id" => 4],
            ["id" => 195, "nombre" => "paso de indios", "provincia_id" => 4],
            ["id" => 196, "nombre" => "telsen", "provincia_id" => 4],
            ["id" => 197, "nombre" => "languiñeo", "provincia_id" => 4],
            ["id" => 198, "nombre" => "gastre", "provincia_id" => 4],
            ["id" => 199, "nombre" => "futaleufu", "provincia_id" => 4],
            ["id" => 200, "nombre" => "tehuelches", "provincia_id" => 4],
            ["id" => 201, "nombre" => "rawson", "provincia_id" => 4],
            ["id" => 202, "nombre" => "biedma", "provincia_id" => 4],

            ["id" => 203, "nombre" => "rio cuarto", "provincia_id" => 5],
            ["id" => 204, "nombre" => "totoral", "provincia_id" => 5],
            ["id" => 205, "nombre" => "colon", "provincia_id" => 5],
            ["id" => 206, "nombre" => "minas", "provincia_id" => 5],
            ["id" => 207, "nombre" => "punilla", "provincia_id" => 5],
            ["id" => 208, "nombre" => "juarez celman", "provincia_id" => 5],
            ["id" => 209, "nombre" => "marcos juarez", "provincia_id" => 5],
            ["id" => 210, "nombre" => "san justo", "provincia_id" => 5],
            ["id" => 211, "nombre" => "tercero arriba", "provincia_id" => 5],
            ["id" => 212, "nombre" => "rio seco", "provincia_id" => 5],
            ["id" => 213, "nombre" => "capital", "provincia_id" => 5],
            ["id" => 214, "nombre" => "santa maria", "provincia_id" => 5],
            ["id" => 215, "nombre" => "san alberto", "provincia_id" => 5],
            ["id" => 216, "nombre" => "union", "provincia_id" => 5],
            ["id" => 217, "nombre" => "pocho", "provincia_id" => 5],
            ["id" => 218, "nombre" => "calamuchita", "provincia_id" => 5],
            ["id" => 219, "nombre" => "ischilin", "provincia_id" => 5],
            ["id" => 220, "nombre" => "general san martin", "provincia_id" => 5],
            ["id" => 221, "nombre" => "rio primero", "provincia_id" => 5],
            ["id" => 222, "nombre" => "cruz del eje", "provincia_id" => 5],
            ["id" => 223, "nombre" => "grl.roca", "provincia_id" => 5],
            ["id" => 224, "nombre" => "general roca", "provincia_id" => 5],
            ["id" => 225, "nombre" => "sobremonte", "provincia_id" => 5],
            ["id" => 226, "nombre" => "rio segundo", "provincia_id" => 5],
            ["id" => 227, "nombre" => "tulumba", "provincia_id" => 5],
            ["id" => 228, "nombre" => "san javier", "provincia_id" => 5],
            ["id" => 229, "nombre" => "presidente roque saez peña", "provincia_id" => 5],
            ["id" => 230, "nombre" => "presidente roque saenz peña", "provincia_id" => 5],
            ["id" => 232, "nombre" => "cruz de eje", "provincia_id" => 5],
            ["id" => 233, "nombre" => "coronel pringles", "provincia_id" => 5],
            ["id" => 234, "nombre" => "rio tercero", "provincia_id" => 5],
            // ["id" => 235, "nombre" => "cvalamuchita", "provincia_id" => 5],

            ["id" => 236, "nombre" => "san roque", "provincia_id" => 6],
            ["id" => 237, "nombre" => "monte caseros", "provincia_id" => 6],
            ["id" => 238, "nombre" => "general alvear", "provincia_id" => 6],
            ["id" => 239, "nombre" => "curuzu cuatia", "provincia_id" => 6],
            ["id" => 240, "nombre" => "san martin", "provincia_id" => 6],
            ["id" => 241, "nombre" => "mercedes", "provincia_id" => 6],
            ["id" => 242, "nombre" => "saladas", "provincia_id" => 6],
            ["id" => 243, "nombre" => "ituzaingo", "provincia_id" => 6],
            ["id" => 244, "nombre" => "beron de astrada", "provincia_id" => 6],
            ["id" => 245, "nombre" => "bella vista", "provincia_id" => 6],
            ["id" => 246, "nombre" => "san luis del palmar", "provincia_id" => 6],
            ["id" => 247, "nombre" => "capital", "provincia_id" => 6],
            ["id" => 248, "nombre" => "lavalle", "provincia_id" => 6],
            ["id" => 249, "nombre" => "paso de los libres", "provincia_id" => 6],
            ["id" => 250, "nombre" => "goya", "provincia_id" => 6],
            ["id" => 251, "nombre" => "empedrado", "provincia_id" => 6],
            ["id" => 252, "nombre" => "sauce", "provincia_id" => 6],
            ["id" => 253, "nombre" => "general paz", "provincia_id" => 6],
            ["id" => 254, "nombre" => "santo tome", "provincia_id" => 6],
            ["id" => 255, "nombre" => "san miguel", "provincia_id" => 6],
            ["id" => 256, "nombre" => "concepcion", "provincia_id" => 6],
            ["id" => 257, "nombre" => "esquina", "provincia_id" => 6],
            ["id" => 258, "nombre" => "san cosme", "provincia_id" => 6],
            ["id" => 259, "nombre" => "itati", "provincia_id" => 6],
            ["id" => 260, "nombre" => "mburucuya", "provincia_id" => 6],

            ["id" => 261, "nombre" => "uruguay", "provincia_id" => 7],
            ["id" => 262, "nombre" => "nogoya", "provincia_id" => 7],
            ["id" => 263, "nombre" => "tala", "provincia_id" => 7],
            ["id" => 264, "nombre" => "gualeguay", "provincia_id" => 7],
            ["id" => 265, "nombre" => "diamante", "provincia_id" => 7],
            ["id" => 266, "nombre" => "parana", "provincia_id" => 7],
            ["id" => 267, "nombre" => "gualeguaychu", "provincia_id" => 7],
            ["id" => 268, "nombre" => "colon", "provincia_id" => 7],
            ["id" => 269, "nombre" => "victoria", "provincia_id" => 7],
            ["id" => 270, "nombre" => "villaguay", "provincia_id" => 7],
            ["id" => 271, "nombre" => "feliciano", "provincia_id" => 7],
            ["id" => 272, "nombre" => "concordia", "provincia_id" => 7],
            ["id" => 273, "nombre" => "la paz", "provincia_id" => 7],
            ["id" => 274, "nombre" => "federacion", "provincia_id" => 7],
            ["id" => 275, "nombre" => "federal", "provincia_id" => 7],
            ["id" => 276, "nombre" => "castellanos", "provincia_id" => 7],

            ["id" => 277, "nombre" => "pilagas", "provincia_id" => 8],
            ["id" => 278, "nombre" => "patiño", "provincia_id" => 8],
            ["id" => 279, "nombre" => "pilcomayo", "provincia_id" => 8],
            ["id" => 280, "nombre" => "bermejo", "provincia_id" => 8],
            ["id" => 281, "nombre" => "pirane", "provincia_id" => 8],
            ["id" => 282, "nombre" => "formosa", "provincia_id" => 8],
            ["id" => 283, "nombre" => "matacos", "provincia_id" => 8],
            ["id" => 284, "nombre" => "ramon lista", "provincia_id" => 8],
            ["id" => 285, "nombre" => "pillagas", "provincia_id" => 8],
            ["id" => 286, "nombre" => "laishi", "provincia_id" => 8],

            ["id" => 287, "nombre" => "ledesma", "provincia_id" => 9],
            ["id" => 288, "nombre" => "cochinoca", "provincia_id" => 9],
            ["id" => 289, "nombre" => "el carmen", "provincia_id" => 9],
            ["id" => 290, "nombre" => "tumbaya", "provincia_id" => 9],
            ["id" => 291, "nombre" => "capital", "provincia_id" => 9],
            ["id" => 292, "nombre" => "yavi", "provincia_id" => 9],
            ["id" => 293, "nombre" => "humahuaca", "provincia_id" => 9],
            ["id" => 294, "nombre" => "rinconada", "provincia_id" => 9],
            ["id" => 295, "nombre" => "valle grande", "provincia_id" => 9],
            ["id" => 296, "nombre" => "susques", "provincia_id" => 9],
            ["id" => 297, "nombre" => "santa catalina", "provincia_id" => 9],
            ["id" => 298, "nombre" => "san antonio", "provincia_id" => 9],
            ["id" => 299, "nombre" => "santa barbara", "provincia_id" => 9],
            ["id" => 300, "nombre" => "san pedro", "provincia_id" => 9],
            ["id" => 301, "nombre" => "tilcara", "provincia_id" => 9],
            ["id" => 302, "nombre" => "ladesma", "provincia_id" => 9],

            ["id" => 303, "nombre" => "hucal", "provincia_id" => 10],
            ["id" => 304, "nombre" => "realico", "provincia_id" => 10],
            ["id" => 305, "nombre" => "mara co", "provincia_id" => 10],
            ["id" => 306, "nombre" => "quemuquemu", "provincia_id" => 10],
            ["id" => 307, "nombre" => "chical co", "provincia_id" => 10],
            ["id" => 308, "nombre" => "guatrache", "provincia_id" => 10],
            ["id" => 309, "nombre" => "capital", "provincia_id" => 10],
            ["id" => 310, "nombre" => "caleucaleu", "provincia_id" => 10],
            ["id" => 311, "nombre" => "trenel", "provincia_id" => 10],
            ["id" => 312, "nombre" => "utracan", "provincia_id" => 10],
            ["id" => 313, "nombre" => "atreuco", "provincia_id" => 10],
            ["id" => 314, "nombre" => "toay", "provincia_id" => 10],
            ["id" => 315, "nombre" => "chapadleufu", "provincia_id" => 10],
            ["id" => 316, "nombre" => "conelo", "provincia_id" => 10],
            ["id" => 317, "nombre" => "puelen", "provincia_id" => 10],
            ["id" => 318, "nombre" => "rancul", "provincia_id" => 10],
            ["id" => 319, "nombre" => "quemu quemu", "provincia_id" => 10],
            ["id" => 320, "nombre" => "loventue", "provincia_id" => 10],
            ["id" => 321, "nombre" => "conhelo", "provincia_id" => 10],
            ["id" => 322, "nombre" => "catrilo", "provincia_id" => 10],
            ["id" => 323, "nombre" => "chapaleufu", "provincia_id" => 10],
            ["id" => 324, "nombre" => "ultracan", "provincia_id" => 10],
            ["id" => 325, "nombre" => "chalileo", "provincia_id" => 10],
            ["id" => 326, "nombre" => "lihuel calel", "provincia_id" => 10],
            ["id" => 327, "nombre" => "maraco", "provincia_id" => 10],
            ["id" => 328, "nombre" => "caleu caleu", "provincia_id" => 10],
            ["id" => 329, "nombre" => "curaco", "provincia_id" => 10],
            ["id" => 330, "nombre" => "limay mahuida", "provincia_id" => 10],

            ["id" => 331, "nombre" => "castro barros", "provincia_id" => 11],
            ["id" => 332, "nombre" => "general san martin", "provincia_id" => 11],
            ["id" => 333, "nombre" => "general lavalle", "provincia_id" => 11],
            ["id" => 334, "nombre" => "arauco", "provincia_id" => 11],
            ["id" => 335, "nombre" => "gral.angel v.peñaloza", "provincia_id" => 11],
            ["id" => 336, "nombre" => "san blas de los sauces", "provincia_id" => 11],
            ["id" => 337, "nombre" => "independencia", "provincia_id" => 11],
            ["id" => 338, "nombre" => "general ocampo", "provincia_id" => 11],
            ["id" => 339, "nombre" => "chilecito", "provincia_id" => 11],
            ["id" => 340, "nombre" => "famatina", "provincia_id" => 11],
            ["id" => 341, "nombre" => "grl.juan facundo quiroga", "provincia_id" => 11],
            ["id" => 342, "nombre" => "grl.angel v. peñaloza", "provincia_id" => 11],
            ["id" => 343, "nombre" => "general belgrano", "provincia_id" => 11],
            ["id" => 344, "nombre" => "general sarmiento", "provincia_id" => 11],
            ["id" => 345, "nombre" => "capital", "provincia_id" => 11],
            ["id" => 346, "nombre" => "gdor. gordillo", "provincia_id" => 11],
            ["id" => 347, "nombre" => "general angel vicente peñaloza", "provincia_id" => 11],
            ["id" => 348, "nombre" => "gobernador gordillo", "provincia_id" => 11],
            ["id" => 349, "nombre" => "rosario vera peñaloza", "provincia_id" => 11],
            ["id" => 350, "nombre" => "grl.san martin", "provincia_id" => 11],
            ["id" => 351, "nombre" => "general la madrid", "provincia_id" => 11],
            ["id" => 352, "nombre" => "general juan facundo quiroga", "provincia_id" => 11],
            ["id" => 353, "nombre" => "generalocampo", "provincia_id" => 11],
            ["id" => 354, "nombre" => "sanagasta", "provincia_id" => 11],

            ["id" => 355, "nombre" => "san rafael", "provincia_id" => 12],
            ["id" => 356, "nombre" => "lujan", "provincia_id" => 12],
            ["id" => 357, "nombre" => "malargue", "provincia_id" => 12],
            ["id" => 358, "nombre" => "guaymallen", "provincia_id" => 12],
            ["id" => 359, "nombre" => "lavalle", "provincia_id" => 12],
            ["id" => 360, "nombre" => "junin", "provincia_id" => 12],
            ["id" => 361, "nombre" => "tupungato", "provincia_id" => 12],
            ["id" => 362, "nombre" => "rivadavia", "provincia_id" => 12],
            ["id" => 363, "nombre" => "maipu", "provincia_id" => 12],
            ["id" => 364, "nombre" => "godoy cruz", "provincia_id" => 12],
            ["id" => 365, "nombre" => "general alvear", "provincia_id" => 12],
            ["id" => 366, "nombre" => "la paz", "provincia_id" => 12],
            ["id" => 367, "nombre" => "tunuyan", "provincia_id" => 12],
            ["id" => 368, "nombre" => "san carlos", "provincia_id" => 12],
            ["id" => 369, "nombre" => "las heras", "provincia_id" => 12],
            ["id" => 370, "nombre" => "lujan de cuyo", "provincia_id" => 12],
            ["id" => 371, "nombre" => "san martin", "provincia_id" => 12],
            ["id" => 372, "nombre" => "santa rosa", "provincia_id" => 12],
            ["id" => 373, "nombre" => "capital", "provincia_id" => 12],

            ["id" => 374, "nombre" => "25 de mayo", "provincia_id" => 13],
            ["id" => 375, "nombre" => "iguazu", "provincia_id" => 13],
            ["id" => 376, "nombre" => "el dorado", "provincia_id" => 13],
            ["id" => 377, "nombre" => "leandro n. alem", "provincia_id" => 13],
            ["id" => 378, "nombre" => "apostoles", "provincia_id" => 13],
            ["id" => 379, "nombre" => "cainguas", "provincia_id" => 13],
            ["id" => 380, "nombre" => "leandro n.alem", "provincia_id" => 13],
            ["id" => 381, "nombre" => "concepcion", "provincia_id" => 13],
            ["id" => 382, "nombre" => "san pedro", "provincia_id" => 13],
            ["id" => 383, "nombre" => "candelaria", "provincia_id" => 13],
            ["id" => 384, "nombre" => "grl.manuel belgrano", "provincia_id" => 13],
            ["id" => 385, "nombre" => "obera", "provincia_id" => 13],
            ["id" => 386, "nombre" => "libertador grl.san martin", "provincia_id" => 13],
            ["id" => 387, "nombre" => "san ignacio", "provincia_id" => 13],
            ["id" => 388, "nombre" => "montecarlo", "provincia_id" => 13],
            ["id" => 389, "nombre" => "general manuel belgrano", "provincia_id" => 13],
            ["id" => 390, "nombre" => "lebertador grl.san martin", "provincia_id" => 13],
            ["id" => 391, "nombre" => "el guarani", "provincia_id" => 13],
            ["id" => 392, "nombre" => "eldorado", "provincia_id" => 13],
            ["id" => 393, "nombre" => "capital", "provincia_id" => 13],
            ["id" => 394, "nombre" => "guarani", "provincia_id" => 13],
            ["id" => 395, "nombre" => "san javier", "provincia_id" => 13],
            ["id" => 396, "nombre" => "libertador grl. san martin", "provincia_id" => 13],

            ["id" => 397, "nombre" => "collon cura", "provincia_id" => 14],
            ["id" => 398, "nombre" => "alumine", "provincia_id" => 14],
            ["id" => 399, "nombre" => "minas", "provincia_id" => 14],
            ["id" => 400, "nombre" => "añelo", "provincia_id" => 14],
            ["id" => 401, "nombre" => "confluencia", "provincia_id" => 14],
            ["id" => 402, "nombre" => "chos malal", "provincia_id" => 14],
            ["id" => 403, "nombre" => "picunches", "provincia_id" => 14],
            //["id" => 404, "nombre" => "norquin", "provincia_id" => 14],
            ["id" => 405, "nombre" => "pehuenches", "provincia_id" => 14],
            ["id" => 406, "nombre" => "loncopue", "provincia_id" => 14],
            ["id" => 407, "nombre" => "huiliches", "provincia_id" => 14],
            ["id" => 408, "nombre" => "zapala", "provincia_id" => 14],
            ["id" => 409, "nombre" => "catan lil", "provincia_id" => 14],
            ["id" => 410, "nombre" => "ñorquin", "provincia_id" => 14],
            ["id" => 411, "nombre" => "los lagos", "provincia_id" => 14],
            ["id" => 412, "nombre" => "picun leufu", "provincia_id" => 14],
            ["id" => 413, "nombre" => "lacar", "provincia_id" => 14],
            //["id" => 414, "nombre" => "ñoequin", "provincia_id" => 14],

            ["id" => 415, "nombre" => "valcheta", "provincia_id" => 15],
            ["id" => 416, "nombre" => "25 de mayo", "provincia_id" => 15],
            ["id" => 417, "nombre" => "el cuy", "provincia_id" => 15],
            ["id" => 418, "nombre" => "ñorquinco", "provincia_id" => 15],
            ["id" => 419, "nombre" => "general roca", "provincia_id" => 15],
            ["id" => 420, "nombre" => "avellaneda", "provincia_id" => 15],
            ["id" => 421, "nombre" => "conesa", "provincia_id" => 15],
            ["id" => 422, "nombre" => "pichi mahuida", "provincia_id" => 15],
            ["id" => 423, "nombre" => "san antonio", "provincia_id" => 15],
            ["id" => 424, "nombre" => "pilcaniyeu", "provincia_id" => 15],
            ["id" => 425, "nombre" => "9 de julio", "provincia_id" => 15],
            ["id" => 426, "nombre" => "adolfo alsina", "provincia_id" => 15],
            ["id" => 427, "nombre" => "bariloche", "provincia_id" => 15],
            ["id" => 428, "nombre" => "pihi mahuida", "provincia_id" => 15],

            ["id" => 429, "nombre" => "la viña", "provincia_id" => 16],
            ["id" => 430, "nombre" => "san martin", "provincia_id" => 16],
            ["id" => 431, "nombre" => "oran", "provincia_id" => 16],
            ["id" => 432, "nombre" => "anta", "provincia_id" => 16],
            ["id" => 433, "nombre" => "gral.jose de san martin", "provincia_id" => 16],
            ["id" => 434, "nombre" => "guachipas", "provincia_id" => 16],
            ["id" => 435, "nombre" => "rosario de la frontera", "provincia_id" => 16],
            ["id" => 436, "nombre" => "rivadavia", "provincia_id" => 16],
            ["id" => 437, "nombre" => "metan", "provincia_id" => 16],
            ["id" => 438, "nombre" => "san carlos", "provincia_id" => 16],
            ["id" => 439, "nombre" => "grl.guemes", "provincia_id" => 16],
            ["id" => 440, "nombre" => "cachi", "provincia_id" => 16],
            ["id" => 441, "nombre" => "rosario de lerma", "provincia_id" => 16],
            ["id" => 442, "nombre" => "cafayate", "provincia_id" => 16],
            ["id" => 443, "nombre" => "los andes", "provincia_id" => 16],
            ["id" => 444, "nombre" => "grl.jose de san martin", "provincia_id" => 16],
            ["id" => 445, "nombre" => "capital", "provincia_id" => 16],
            ["id" => 446, "nombre" => "grl.san martin", "provincia_id" => 16],
            ["id" => 447, "nombre" => "general guemes", "provincia_id" => 16],
            ["id" => 448, "nombre" => "cerrillos", "provincia_id" => 16],
            ["id" => 449, "nombre" => "chicoana", "provincia_id" => 16],
            ["id" => 450, "nombre" => "la poma", "provincia_id" => 16],
            ["id" => 451, "nombre" => "la capital", "provincia_id" => 16],
            ["id" => 452, "nombre" => "candelaria", "provincia_id" => 16],
            ["id" => 453, "nombre" => "rosario", "provincia_id" => 16],
            ["id" => 454, "nombre" => "iruya", "provincia_id" => 16],
            ["id" => 455, "nombre" => "la caldera", "provincia_id" => 16],
            ["id" => 456, "nombre" => "loa andes", "provincia_id" => 16],
            ["id" => 457, "nombre" => "molinos", "provincia_id" => 16],
            ["id" => 458, "nombre" => "santa victoria", "provincia_id" => 16],

            ["id" => 459, "nombre" => "9 de julio", "provincia_id" => 17],
            ["id" => 460, "nombre" => "jachal", "provincia_id" => 17],
            ["id" => 461, "nombre" => "albardon", "provincia_id" => 17],
            ["id" => 462, "nombre" => "25 de mayo", "provincia_id" => 17],
            ["id" => 463, "nombre" => "santa lucia", "provincia_id" => 17],
            ["id" => 464, "nombre" => "angaco", "provincia_id" => 17],
            ["id" => 465, "nombre" => "iglesia", "provincia_id" => 17],
            ["id" => 466, "nombre" => "valle fertil", "provincia_id" => 17],
            ["id" => 467, "nombre" => "calingasta", "provincia_id" => 17],
            ["id" => 468, "nombre" => "rivadavia", "provincia_id" => 17],
            ["id" => 469, "nombre" => "caucete", "provincia_id" => 17],
            ["id" => 470, "nombre" => "sarmiento", "provincia_id" => 17],
            ["id" => 471, "nombre" => "pocito", "provincia_id" => 17],
            ["id" => 472, "nombre" => "san martin", "provincia_id" => 17],
            ["id" => 473, "nombre" => "chimbas", "provincia_id" => 17],
            ["id" => 474, "nombre" => "iglesias", "provincia_id" => 17],
            ["id" => 475, "nombre" => "ullun", "provincia_id" => 17],
            ["id" => 476, "nombre" => "rawson", "provincia_id" => 17],
            ["id" => 477, "nombre" => "capital", "provincia_id" => 17],
            ["id" => 478, "nombre" => "zonda", "provincia_id" => 17],

            ["id" => 479, "nombre" => "belgrano", "provincia_id" => 18],
            ["id" => 480, "nombre" => "chacabuco", "provincia_id" => 18],
            ["id" => 481, "nombre" => "la capital", "provincia_id" => 18],
            ["id" => 482, "nombre" => "gobernador dupuy", "provincia_id" => 18],
            ["id" => 483, "nombre" => "grl.pedernera", "provincia_id" => 18],
            ["id" => 484, "nombre" => "ayacucho", "provincia_id" => 18],
            ["id" => 485, "nombre" => "junin", "provincia_id" => 18],
            ["id" => 486, "nombre" => "gonernador dupuy", "provincia_id" => 18],
            ["id" => 487, "nombre" => "coronel pringles", "provincia_id" => 18],
            ["id" => 488, "nombre" => "general pedernera", "provincia_id" => 18],
            ["id" => 489, "nombre" => "gobernador duval", "provincia_id" => 18],
            ["id" => 490, "nombre" => "iglesia", "provincia_id" => 18],
            ["id" => 491, "nombre" => "libertador grl. san martin", "provincia_id" => 18],
            ["id" => 492, "nombre" => "libertador grl.san martin", "provincia_id" => 18],
            ["id" => 493, "nombre" => "libertador gr.san martin", "provincia_id" => 18],
            ["id" => 494, "nombre" => "caucete", "provincia_id" => 18],

            ["id" => 495, "nombre" => "guer aike", "provincia_id" => 19],
            ["id" => 496, "nombre" => "deseado", "provincia_id" => 19],
            ["id" => 497, "nombre" => "rio chico", "provincia_id" => 19],
            ["id" => 498, "nombre" => "magallanes", "provincia_id" => 19],
            ["id" => 499, "nombre" => "lago argentino", "provincia_id" => 19],
            ["id" => 500, "nombre" => "corpen aike", "provincia_id" => 19],
            ["id" => 501, "nombre" => "lago buenos aires", "provincia_id" => 19],

            ["id" => 502, "nombre" => "general lopez", "provincia_id" => 20],
            ["id" => 503, "nombre" => "rosario", "provincia_id" => 20],
            ["id" => 504, "nombre" => "general obligado", "provincia_id" => 20],
            ["id" => 505, "nombre" => "constitucion", "provincia_id" => 20],
            ["id" => 506, "nombre" => "san lorenzo", "provincia_id" => 20],
            ["id" => 507, "nombre" => "san javier", "provincia_id" => 20],
            ["id" => 508, "nombre" => "la capital", "provincia_id" => 20],
            ["id" => 509, "nombre" => "san cristobal", "provincia_id" => 20],
            ["id" => 510, "nombre" => "iriondo", "provincia_id" => 20],
            ["id" => 511, "nombre" => "castellanos", "provincia_id" => 20],
            ["id" => 512, "nombre" => "nueve de julio", "provincia_id" => 20],
            ["id" => 513, "nombre" => "caseros", "provincia_id" => 20],
            ["id" => 514, "nombre" => "san jeronimo", "provincia_id" => 20],
            ["id" => 515, "nombre" => "belgrano", "provincia_id" => 20],
            ["id" => 516, "nombre" => "capital", "provincia_id" => 20],
            ["id" => 517, "nombre" => "san justo", "provincia_id" => 20],
            ["id" => 518, "nombre" => "grl.obligado", "provincia_id" => 20],
            ["id" => 519, "nombre" => "la caputal", "provincia_id" => 20],
            ["id" => 520, "nombre" => "grl.lopez", "provincia_id" => 20],
            ["id" => 521, "nombre" => "vera", "provincia_id" => 20],
            ["id" => 522, "nombre" => "9 de julio", "provincia_id" => 20],
            ["id" => 523, "nombre" => "san martin", "provincia_id" => 20],
            ["id" => 524, "nombre" => "las colonias", "provincia_id" => 20],
            ["id" => 525, "nombre" => "garay", "provincia_id" => 20],
            ["id" => 526, "nombre" => "castelanos", "provincia_id" => 20],
            ["id" => 527, "nombre" => "las colinas", "provincia_id" => 20],

            ["id" => 528, "nombre" => "banda", "provincia_id" => 21],
            ["id" => 529, "nombre" => "moreno", "provincia_id" => 21],
            ["id" => 530, "nombre" => "alberdi", "provincia_id" => 21],
            ["id" => 531, "nombre" => "pellegrini", "provincia_id" => 21],
            ["id" => 532, "nombre" => "ojo de agua", "provincia_id" => 21],
            ["id" => 533, "nombre" => "rio hondo", "provincia_id" => 21],
            ["id" => 534, "nombre" => "general taboada", "provincia_id" => 21],
            ["id" => 535, "nombre" => "choya", "provincia_id" => 21],
            ["id" => 536, "nombre" => "capital", "provincia_id" => 21],
            ["id" => 537, "nombre" => "aguirre", "provincia_id" => 21],
            ["id" => 538, "nombre" => "silipica", "provincia_id" => 21],
            ["id" => 539, "nombre" => "belgrano", "provincia_id" => 21],
            ["id" => 540, "nombre" => "figueroa", "provincia_id" => 21],
            ["id" => 541, "nombre" => "salavina", "provincia_id" => 21],
            ["id" => 542, "nombre" => "quebrachos", "provincia_id" => 21],
            ["id" => 543, "nombre" => "robles", "provincia_id" => 21],
            ["id" => 544, "nombre" => "avellaneda", "provincia_id" => 21],
            ["id" => 545, "nombre" => "jimenez", "provincia_id" => 21],
            ["id" => 546, "nombre" => "atamisqui", "provincia_id" => 21],
            ["id" => 547, "nombre" => "san martin", "provincia_id" => 21],
            ["id" => 548, "nombre" => "matara", "provincia_id" => 21],
            ["id" => 549, "nombre" => "salayina", "provincia_id" => 21],
            ["id" => 550, "nombre" => "guasayan", "provincia_id" => 21],
            ["id" => 551, "nombre" => "copo", "provincia_id" => 21],
            ["id" => 552, "nombre" => "brigadier juan felipe ibarra", "provincia_id" => 21],
            ["id" => 553, "nombre" => "dobles", "provincia_id" => 21],
            ["id" => 554, "nombre" => "sarmiento", "provincia_id" => 21],
            ["id" => 555, "nombre" => "loreto", "provincia_id" => 21],
            ["id" => 556, "nombre" => "mitre", "provincia_id" => 21],
            ["id" => 557, "nombre" => "rivadavia", "provincia_id" => 21],

            ["id" => 558, "nombre" => "ushuaia", "provincia_id" => 22],
            ["id" => 559, "nombre" => "islas del atlantico sur", "provincia_id" => 22],
            ["id" => 560, "nombre" => "sector antartico argentino", "provincia_id" => 22],
            ["id" => 561, "nombre" => "rio grande", "provincia_id" => 22],
            ["id" => 562, "nombre" => "is.del atlantico sur e is.malvinas", "provincia_id" => 22],
            ["id" => 563, "nombre" => "antartida argentina", "provincia_id" => 22],

            ["id" => 564, "nombre" => "burruyacu", "provincia_id" => 23],
            ["id" => 565, "nombre" => "trancas", "provincia_id" => 23],
            ["id" => 566, "nombre" => "monteros", "provincia_id" => 23],
            ["id" => 567, "nombre" => "leales", "provincia_id" => 23],
            ["id" => 568, "nombre" => "cruz alta", "provincia_id" => 23],
            ["id" => 569, "nombre" => "rio chico", "provincia_id" => 23],
            ["id" => 570, "nombre" => "chicligasta", "provincia_id" => 23],
            ["id" => 571, "nombre" => "tafi", "provincia_id" => 23],
            ["id" => 572, "nombre" => "graneros", "provincia_id" => 23],
            ["id" => 573, "nombre" => "famailla", "provincia_id" => 23],
            ["id" => 574, "nombre" => "capital", "provincia_id" => 23],
            
            ["id" => 575, "nombre" => "capital federal", "provincia_id" => 1]
        ));
    }
}
